## Data Loading and Preprocessing

### Data Loading
Keras models accept three types of inputs:
- Numpy arrays
- TensorFlow ```Dataset``` objects
- Python generators

To turn raw data on disk into a ```Dataset```, the following utility can be used:
- ```tf.keras.preprocessing.image_dataset_from_directory```. This turn image files sorted into class-specific folders into a labeled dataset of image tensors

TensorFlow `tf.data` includes `tf.data.experimental.make_csv_dataset` to load structured data from CSV files

### Preprocessing
Preprocessing in Keras includes:
- Feature normalization via the ```Normalization``` layer
- Image Rescaling, cropping, or image data augmentation

## Keras Functional API

A "layer" is a simple input-output transformation. A "model" is a acyclic graph of layers.

## Tensors

TensorFlow is an infrastructure layer for differentiable programming. 

In [3]:
import tensorflow as tf
from tensorflow import keras

x = tf.constant([[10, 20], [1, 2]])
print(x)

tf.Tensor(
[[10 20]
 [ 1  2]], shape=(2, 2), dtype=int32)


In [4]:
x.numpy()

array([[10, 20],
       [ 1,  2]], dtype=int32)

In [6]:
print(x.shape)
print(x.dtype)

(2, 2)
<dtype: 'int32'>


In [7]:
print(tf.ones(shape = (4,4)))
print(tf.zeros(shape = (4,4)))

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)


In [8]:
tf.ones(shape = (4,4)) + tf.zeros(shape = (4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [9]:
tf.random.normal(shape = (4,4), mean = 0.0, stddev = 1.0)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.42100772,  0.8647848 ,  0.3144814 ,  0.21292281],
       [ 1.7744913 , -0.5420868 , -0.27176502,  0.72439367],
       [-0.57539856,  0.66884786, -0.5827226 , -0.0887428 ],
       [-0.16719991,  0.05323338,  1.1693333 ,  0.04671806]],
      dtype=float32)>

In [11]:
tf.random.uniform(shape = (4,4), minval = 0, maxval = 255, dtype = "int32")

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[148, 154, 100, 108],
       [234,  54, 212,  49],
       [241,  69, 225,  17],
       [153,  86,  95,  28]], dtype=int32)>